variables:
  #Azure DevOps (azdo) variables 
  azdoServiceConnection: azdo-serviceconnection-arm-d
  azdoEnvironment: Default-Map
  deploymentDirectoryPath: "devops/pipelines/dataproduct/deployment/map"
  deploymentDefinitionsPath: "devops/pipelines/dataproduct/deployment/map/definitions"
