trigger: none

# resources:
#   repositories:
#     - repository: RTD
#       type: git
#       name: RTD/RTD
#       ref: "$(Build.SourceBranch)"
#       endpoint: CrossOrganizationAccess

pool:
  vmImage: "windows-latest"

parameters:

- name: workspaceName
  displayName: "Fabric Workspace(s) Name"
  type: string
  default: "AutoDeploymentDemo" 

- name: semanticModelsBinding
  displayName: "Semantic Model Binding"
  type: string
  default: "[]" 

- name: postDeploymentFolder
  displayName: "Post-deployment folder"
  type: string
  default: "Vertipaq" 

- name: enableDiagnostics
  displayName: "Enable Diagnostics?"
  type: boolean
  default: False

stages:
  - stage: UpdateFromGit
    displayName: Update From Git
    variables:
      - template: ./deployment/variables.yml

    jobs:
    - deployment: Deploy
      displayName: Update ${{ parameters.workspaceName }} from Git
      environment: ${{variables.azdoEnvironment}}
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: none

              - task: FabricCatalystUpdateFromGit@1
                displayName: 'FabricCatalyst - Auto Deployment'
                inputs:
                  azureSubscription: ${{ variables.azdoServiceConnection }}
                  fabricGitConnectionName: ${{ variables.fabricGitConnectionName }}
                  workspaceName: ${{ parameters.workspaceName }}
                  semanticModelsBinding: ${{ parameters.semanticModelsBinding }}
                  postDeploymentFolder: ${{ parameters.postDeploymentFolder }}
                  enableDiagnostics: ${{ parameters.enableDiagnostics }}