variables:
  #Azure DevOps (azdo) variables
  azdoServiceConnection: azdo-serviceconnection-arm-d
  azdoEnvironment: publish_extension

  #Azure Key Vault (holds the Personal Access Token used by tfx extension publish)
  keyVaultName: "fabcat-shared-d-kv"
  extensionPatSecretName: scrt-vsts-publish-token
  extensionPatSecretVersion: f4278e22a73c4f3fb5c19f3c14305833
